// Generated by scripts/dump-oracle-fixtures.py: block time of the slot the accounts were read at.
pub const ORACLE_SNAPSHOT_SLOT: u64 = 451436676;
pub const ORACLE_SNAPSHOT_UNIX_TIMESTAMP: i64 = 1790630048;
