//! Mainnet programs and accounts captured into `fixtures/mainnet/` (regenerated by
//! `scripts/dump-mainnet-fixtures.py`) and loaded into LiteSVM as-is.

use super::*;
use flate2::read::GzDecoder;
use litesvm::LiteSVM;
use solana_account::Account as SvmAccount;
use std::io::Read;

include!("../fixtures/mainnet/snapshot.rs");

/// Unix time the clock is pinned to: the snapshot's own block time. Every captured timestamp
/// (klend deposit-cap windows, Orca reward updates) is at or before it, and klend, which accrues
/// interest by elapsed time inside supply and redeem, sees at most seconds to accrue, so its
/// exchange rate matches the capture.
pub const FIXTURE_UNIX_TIMESTAMP: i64 = SNAPSHOT_UNIX_TIMESTAMP;

macro_rules! account_fixture {
    ($key:literal) => {
        ($key, include_bytes!(concat!("../fixtures/mainnet/", $key, ".acct")).as_slice())
    };
}

/// `owner (32) | lamports (u64 LE) | executable (u8) | data`.
pub(crate) const ACCOUNTS: [(&str, &[u8]); 19] = [
    account_fixture!("7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF"),
    account_fixture!("9DrvZvyWh1HuAoZxvYWMvkf2XCzryCpGgHqrMjyDWpmo"),
    account_fixture!("D6q6wuQSrifJKZYpR1M8R4YawnLDtDsMmWM1NbBmgJ59"),
    account_fixture!("Bgq7trRgVMeq33yt235zM2onQ4bRDBsY5EWiTetF4qw6"),
    account_fixture!("B8V6WVjPxW1UGwVDfxH2d2r8SyT4cqn7dQRK6XneVa7D"),
    account_fixture!("d4A2prbA2whesmvHaL88BH6Ewn5N4bTSU2Ze8P6Bc4Q"),
    account_fixture!("GafNuUXj9rxGLn4y79dPu6MHSuPWeJR6UtTWuexpGh3U"),
    account_fixture!("2UywZrUdyqs5vDchy7fKQJKau2RVyuzBev2XKGPDSiX1"),
    account_fixture!("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"),
    account_fixture!("So11111111111111111111111111111111111111112"),
    account_fixture!("Czfq3xZZDmsdGdUyrNLtRhGc47cXcZtLG4crryfu44zE"),
    account_fixture!("EUuUbDcafPrmVTD5M6qoJAoyyNbihBhugADAxRMn5he9"),
    account_fixture!("2WLWEuKDgkDUccTpbwYp1GToYktiSB1cXvreHUwiSUVP"),
    account_fixture!("FdtvWk8j5u1a64YK2Uxk9eXxKZJTwLHDGx8aJPbJyw2Q"),
    account_fixture!("6hA1LN1fzCiXqymDiQXeBFn5da1b7STP1L7JmDc6hR3M"),
    account_fixture!("D3461zSTVPNdBFPRk2b6zpqQ93g2LW5Kw2potgMdxNJP"),
    account_fixture!("GGztQqQ6pCPaJQnNpXBgELr5cs3WwDakRbh1iEMzjgSJ"),
    account_fixture!("g7dD1FHSemkUQrX1Eak37wzvDjscgBW2pFCENwjLdMX"),
    account_fixture!("DVCeozFGbe6ew3eWTnZByjHeYqTq1cvbrB7JJhkLxaRJ"),
];

const KLEND_ELF_GZ: &[u8] = include_bytes!("../fixtures/mainnet/klend.so.gz");
const JUPITER_ELF_GZ: &[u8] = include_bytes!("../fixtures/mainnet/jupiter.so.gz");
const WHIRLPOOL_ELF_GZ: &[u8] = include_bytes!("../fixtures/mainnet/whirlpool.so.gz");

fn gunzip(bytes: &[u8]) -> Vec<u8> {
    let mut out = Vec::new();
    GzDecoder::new(bytes).read_to_end(&mut out).unwrap();
    out
}

/// Loads Kamino klend, Jupiter v6 and Orca Whirlpool with every captured account, and pins the
/// clock to [`FIXTURE_UNIX_TIMESTAMP`].
pub fn load_mainnet(svm: &mut LiteSVM) {
    svm.add_program(super::kamino::KLEND, &gunzip(KLEND_ELF_GZ)).unwrap();
    svm.add_program(super::jupiter::JUPITER, &gunzip(JUPITER_ELF_GZ)).unwrap();
    svm.add_program(super::jupiter::WHIRLPOOL, &gunzip(WHIRLPOOL_ELF_GZ)).unwrap();
    for (key, blob) in ACCOUNTS {
        let owner = Pubkey::new_from_array(blob[..32].try_into().unwrap());
        let lamports = u64::from_le_bytes(blob[32..40].try_into().unwrap());
        let account = SvmAccount { lamports, data: blob[41..].to_vec(), owner, executable: blob[40] == 1, rent_epoch: 0 };
        svm.set_account(key.parse().unwrap(), account).unwrap();
    }
    let mut clock = svm.get_sysvar::<Clock>();
    clock.unix_timestamp = FIXTURE_UNIX_TIMESTAMP;
    svm.set_sysvar(&clock);
}
