#!/usr/bin/env python3

import argparse
import base64
import json
import os
import struct
import time
import urllib.request

ACCOUNTS = [
    "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH",
    "Dpw1EAVrSB1ibxiDQyTAW6Zip3J4Btk2x4SgApQCeFbX",
    "HT2PLQBcG5EiCcNSaMHAjSgd9F98ecpATbk4Sk5oYuM",
    "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE",
    "AxaxyeDT8JnWERSaTKvFXvPKkEdxnamKSqpWbsSjYg1g",
    "D7UqeBmCEmhGXGYfi2y9RfoCa7t1Xw5iZLBeYZ3sxFSe",
    "AqSwMCZYnEdnGoFCSLtWVnWf4xyCJuePcztmYWq8SBwp",
    "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    "So11111111111111111111111111111111111111112",
    "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn",
    "jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v",
    "JuprjznTrTSp2UFa3ZBUFgwdAmtZCq4MQCwysN55USD",
    "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh",
    "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB",
]
OUT = os.path.join(os.path.dirname(__file__), "..", "programs", "vanna_credit_layer", "src", "tests", "fixtures", "oracles")
B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"

def b58decode(s: str) -> bytes:
    n = 0
    for c in s:
        n = n * 58 + B58.index(c)
    raw = n.to_bytes((n.bit_length() + 7) // 8, "big")
    return b"\0" * (len(s) - len(s.lstrip("1"))) + raw

def rpc_call(rpc: str, method: str, params: list) -> dict:
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params})
    request = urllib.request.Request(rpc, body.encode(), {"Content-Type": "application/json"})
    return json.load(urllib.request.urlopen(request))["result"]

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rpc", default="https://api.mainnet-beta.solana.com")
    rpc = parser.parse_args().rpc
    os.makedirs(OUT, exist_ok=True)

    result = rpc_call(rpc, "getMultipleAccounts", [ACCOUNTS, {"encoding": "base64"}])
    for key, account in zip(ACCOUNTS, result["value"]):
        if account is None:
            raise SystemExit(f"{key} not found")
        data = base64.b64decode(account["data"][0])
        blob = b58decode(account["owner"]) + struct.pack("<Q", account["lamports"]) + bytes([account["executable"]]) + data
        with open(os.path.join(OUT, f"{key}.acct"), "wb") as f:
            f.write(blob)
    slot = result["context"]["slot"]
    block_time = rpc_call(rpc, "getBlockTime", [slot])
    with open(os.path.join(OUT, "snapshot.rs"), "w") as f:
        f.write("// Generated by scripts/dump-oracle-fixtures.py: block time of the slot the accounts were read at.\n")
        f.write(f"pub const ORACLE_SNAPSHOT_SLOT: u64 = {slot};\n")
        f.write(f"pub const ORACLE_SNAPSHOT_UNIX_TIMESTAMP: i64 = {block_time or int(time.time())};\n")
    print(f"{len(ACCOUNTS)} accounts at slot {slot} (block time {block_time})")

if __name__ == "__main__":
    main()
