#!/usr/bin/env python3

import argparse
import base64
import gzip
import json
import os
import struct
import time
import urllib.request

GMTRADE = "Gmso1uvJnLbawvw7yezdfCDcPydwW2s2iqG3w6MDucLo"
ETH_MARKET = "6EnZdBzJsGznoh857PuhbrnrzWYGtZe6xMZiQjAPyFGT"
ETH_MARKET_TOKEN = "DAY6Qr1FKgJQFvjJAhFUZUWHzx8UbbbkRmt6G6AYswWG"
ACCOUNTS = [
    "CTDLvGGXnoxvqLyTpGzdGLg9pD6JexKxKXSV8tqqo8bN",
    ETH_MARKET,
    ETH_MARKET_TOKEN,
    "EthK4kKnQQUd1Ae1w7sdiMAUaJwq2RMwr7AtscXEdEsF",
    "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH",
    "3NJYftD5sjVfxSnUdZ1wVML8f3aC6mp1CXCL6L7TnU8C",
    "Dpw1EAVrSB1ibxiDQyTAW6Zip3J4Btk2x4SgApQCeFbX",
    "42amVS4KgzR9rA28tkVYqVXjq9Qa8dcZQMbH5EYFX6XC",
]
POSITION_LEN = 8 + 672
OUT = os.path.join(os.path.dirname(__file__), "..", "programs", "vanna_credit_layer", "src", "tests", "fixtures", "gmtrade")
B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"

def b58decode(s: str) -> bytes:
    n = 0
    for c in s:
        n = n * 58 + B58.index(c)
    raw = n.to_bytes((n.bit_length() + 7) // 8, "big")
    return b"\0" * (len(s) - len(s.lstrip("1"))) + raw

def b58encode(b: bytes) -> str:
    n = int.from_bytes(b, "big")
    s = ""
    while n:
        n, m = divmod(n, 58)
        s = B58[m] + s
    return "1" * (len(b) - len(b.lstrip(b"\0"))) + s

def rpc_call(rpc: str, method: str, params: list) -> dict:
    body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": method, "params": params})
    request = urllib.request.Request(rpc, body.encode(), {"Content-Type": "application/json"})
    response = json.load(urllib.request.urlopen(request))
    if "error" in response:
        raise SystemExit(f"{method}: {response['error']}")
    return response["result"]

def largest_positions(rpc: str) -> tuple:
    filters = [{"dataSize": POSITION_LEN}, {"memcmp": {"offset": 8 + 80, "bytes": ETH_MARKET_TOKEN}}]
    accounts = rpc_call(rpc, "getProgramAccounts", [GMTRADE, {"encoding": "base64", "filters": filters}])
    best = {1: (0, None), 2: (0, None)}
    for account in accounts:
        data = base64.b64decode(account["account"]["data"][0])
        kind = data[8 + 34]
        size_in_usd = int.from_bytes(data[8 + 208 : 8 + 224], "little")
        if kind in best and size_in_usd > best[kind][0]:
            best[kind] = (size_in_usd, account["pubkey"])
    return best[1][1], best[2][1]

def write_account(key: str, owner: str, lamports: int, executable: bool, data: bytes) -> None:
    blob = b58decode(owner) + struct.pack("<Q", lamports) + bytes([executable]) + data
    with open(os.path.join(OUT, f"{key}.acct"), "wb") as f:
        f.write(blob)

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rpc", default="https://api.mainnet-beta.solana.com")
    rpc = parser.parse_args().rpc
    os.makedirs(OUT, exist_ok=True)

    program = rpc_call(rpc, "getAccountInfo", [GMTRADE, {"encoding": "base64"}])["value"]
    program_data = b58encode(base64.b64decode(program["data"][0])[4:36])
    elf = base64.b64decode(rpc_call(rpc, "getAccountInfo", [program_data, {"encoding": "base64"}])["value"]["data"][0])[45:]
    with open(os.path.join(OUT, "gmsol_store.so.gz"), "wb") as f:
        f.write(gzip.compress(elf, 9))

    long_position, short_position = largest_positions(rpc)
    keys = ACCOUNTS + [long_position, short_position]
    result = rpc_call(rpc, "getMultipleAccounts", [keys, {"encoding": "base64"}])
    for key, account in zip(keys, result["value"]):
        if account is None:
            raise SystemExit(f"{key} not found")
        write_account(key, account["owner"], account["lamports"], account["executable"], base64.b64decode(account["data"][0]))
    slot = result["context"]["slot"]
    block_time = rpc_call(rpc, "getBlockTime", [slot])
    with open(os.path.join(OUT, "snapshot.rs"), "w") as f:
        f.write("// Generated by scripts/dump-gmtrade-fixtures.py: the slot the accounts were read at, its block\n")
        f.write("// time, and the largest live ETH long and short positions.\n")
        f.write(f"pub const GMTRADE_SNAPSHOT_SLOT: u64 = {slot};\n")
        f.write(f"pub const GMTRADE_SNAPSHOT_UNIX_TIMESTAMP: i64 = {block_time or int(time.time())};\n")
        f.write(f'pub const LIVE_LONG_POSITION: &str = "{long_position}";\n')
        f.write(f'pub const LIVE_SHORT_POSITION: &str = "{short_position}";\n')
    print(f"GMTrade ELF {len(elf)} bytes; {len(keys)} accounts at slot {slot} (block time {block_time})")

if __name__ == "__main__":
    main()
